### DISCUSSION TITLE
GSoC 2023: Dask fixes and development.

### DISCUSSION THREAD

**Discussion by adi611** [nipype/pydra#665] [General]
I tried running the example as mentioned in #663 on Dask, and I got the expected result: the required `Output.txt` and `Image.png` files. Here is my code:
```
import nest_asyncio
import pydra

nest_asyncio.apply()

if __name__ ==  '__main__':
    cmd1 = 'pdftotext'
    args = ['/mnt/c/Users/Aditya/OneDrive/Desktop/GSoC/pydra_codes/Week_1_2/content/Lorem_ipsum.pdf', '/mnt/c/Users/Aditya/OneDrive/Desktop/GSoC/pydra_codes/Week_1_2/content/Output.txt']
    
    shelly1 = pydra.ShellCommandTask(name='shelly1', executable=cmd1, args=args)
    print('cmndline = ', shelly1.cmdline)
    
    cmd2 = 'wordcloud_cli'
    args2 = ['--text', '/mnt/c/Users/Aditya/OneDrive/Desktop/GSoC/pydra_codes/Week_1_2/content/Output.txt', '--imagefile', '/mnt/c/Users/Aditya/OneDrive/Desktop/GSoC/pydra_codes/Week_1_2/content/Image.png']
    
    shelly2 = pydra.ShellCommandTask(name='shelly2', executable=cmd2, args=args2)
    print('cmndline = ', shelly2.cmdline)
    
    wf1 = pydra.Workflow(name = 'wf1', input_spec=['x'], x = 'dummy')
    
    wf1.add(shelly1)
    wf1.add(shelly2)
    
    wf1.set_output([('out_s1', wf1.shelly1.lzout.stdout), ('out_s2', wf1.shelly2.lzout.stdout)])
    with pydra.Submitter(plugin='dask') as sub:
        sub(wf1)

    wf1.result()
```
I worked on the code before checking the discussion #664 which mentioned using pytest and relative paths and hence I was unable to do it for this example.

**Comment by djarecka** [comment]
@adi611 - I've checked the pytest command after our discussion, and the option to pytest was correct `--dask`, but I just run it outside the `pydra/engine` directory (and didn't point it to it), and the `--dask` option is defined in conftest that is inside `pydra/engine`, so you can run `pytest -v --dask pydra/engine`. 

you can also start from running for a specific test file, e.g. `pytest --dask -v pydra/engine/tests/test_shelltask.py` or for specific test. 

I tried quckly, and some tests, as expected, are failing, so you should try to figure out how to fix the dask worker.

Let me know if you have questiosn

**Comment by adi611** [comment]
Thank you for your help with this. I have been running `pytest -v --dask pydra/engine` and I always get stuck at the same task `pydra/engine/tests/test_node_task.py::test_task_state_comb_1[dask]` after a `RERUN`. Please let me know if this is an issue in your system as well.
```
====================================================== short test summary info ======================================================
FAILED pydra/engine/tests/test_node_task.py::test_task_state_1[dask-list] - AttributeError: 'tuple' object has no attribute '_run'
FAILED pydra/engine/tests/test_node_task.py::test_task_state_1[dask-array] - AttributeError: 'tuple' object has no attribute '_run'
FAILED pydra/engine/tests/test_node_task.py::test_task_state_comb_1[cf] - OSError: [Errno 24] Too many open files
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/aditya/.local/lib/python3.8/site-packages/filelock/_api.py:199: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
=========================== 3 failed, 219 passed, 74 skipped, 22 warnings, 7 rerun in 1425.20s (0:23:45) ============================
```
Since this seems to be limited to only `test_node_task.py`, I tried running the files individually and so far I encountered no such issue. The pytest coverage for `test_shelltask.py`:
```
====================================================== short test summary info ======================================================
FAILED pydra/engine/tests/test_shelltask.py::test_shell_cmd_3[dask] - AttributeError: 'tuple' object has no attribute '_run'
============================ 1 failed, 36 passed, 124 skipped, 8 warnings, 2 rerun in 137.95s (0:02:17) =============================
[<AsyncProcess Dask Worker process (from Nanny)>] process 11372 exit status was already read will report exitcode 255
[<AsyncProcess Dask Worker process (from Nanny)>] process 11369 exit status was already read will report exitcode 255
```
So far it seems like the same error is present in the failing dask tests: `AttributeError: 'tuple' object has no attribute '_run'`. I will be trying this for all the files and try to come up with a solution for the same.

**Reply by djarecka** [reply]
yes, I was also getting the error, so the worker has to be updated

**Reply by adi611** [reply]
Result for `test_submitter.py`:
```
======================================= 7 passed, 17 skipped, 6 warnings in 99.28s (0:01:39) ========================================
[<AsyncProcess Dask Worker process (from Nanny)>] process 302 exit status was already read will report exitcode 255
Task was destroyed but it is pending!
```
Result for `test_workflow.py`, stuck at `pydra/engine/tests/test_workflow.py::test_wf_3nd_ndst_1[dask]`:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/aditya/.local/lib/python3.8/site-packages/_pytest/logging.py:708: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
====================================== 14 passed, 45 skipped, 19 warnings in 384.25s (0:06:24) ======================================
```
Result for rest of the tests:
```
================================ 414 passed, 81 skipped, 2 xfailed, 4 warnings in 140.84s (0:02:20) =================================
```

**Comment by adi611** [comment]
I added some fixes to the DaskWorker (based on the `ConcurrentFuturesWorker`) and now there is no `AttributeError: 'tuple' object has no attribute '_run'` but some tests are still getting stuck on reruns (for dask), like `pydra/engine/tests/test_workflow.py::test_wf_3nd_ndst_1[dask] RERUN` and `pydra/engine/tests/test_shelltask.py::test_shell_cmd_3[dask] RERUN`. I will look further into this.

**Comment by adi611** [comment]
@djarecka and @ghisvail - As discussed, I checked for all the tests for Dask and only `test_wf_3nd_ndst_1` in `test_workflow.py` hangs ([link to comment and PR](https://github.com/nipype/pydra/pull/673#issuecomment-1634437924)) and I created another PR for adding GitHub Actions workflow for Dask Tests ([link to PR](https://github.com/nipype/pydra/pull/676)).

Please let me know any further steps I should take. Thank you.

**Reply by adi611** [reply]
Apologies for the PR #676. I identified some mistakes in it, and hence I closed it. I wrote a new workflow for testing with Dask, please have a look at the following and let me know whether I should open a PR for this:

```
name: Dask Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
      fail-fast: false

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Checkout Pydra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Install pydra with Dask and test dependencies
        run: |
          pip install -e ".[test,dask]"

      - name: Run tests
        run: |
          pytest -v --dask pydra/engine --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml

      - name: Upload to codecov
        run: codecov -f cov.xml -F unittests -e GITHUB_WORKFLOW
```
